// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/oshizatsu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_SCHEDULED NotificationType = 0
	NotificationType_STARTED   NotificationType = 1
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "SCHEDULED",
		1: "STARTED",
	}
	NotificationType_value = map[string]int32{
		"SCHEDULED": 0,
		"STARTED":   1,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_oshizatsu_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_proto_oshizatsu_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{0}
}

// 認証関連のメッセージ
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserInfoRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UpdateUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Picture       string                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserInfoRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

type UpdateUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoResponse) Reset() {
	*x = UpdateUserInfoResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoResponse) ProtoMessage() {}

func (x *UpdateUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserInfoResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Picture       string                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_oshizatsu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{8}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

// チャンネル関連のメッセージ
type SubscribeChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeChannelRequest) Reset() {
	*x = SubscribeChannelRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeChannelRequest) ProtoMessage() {}

func (x *SubscribeChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeChannelRequest.ProtoReflect.Descriptor instead.
func (*SubscribeChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SubscribeChannelRequest) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *SubscribeChannelRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type SubscribeChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeChannelResponse) Reset() {
	*x = SubscribeChannelResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeChannelResponse) ProtoMessage() {}

func (x *SubscribeChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeChannelResponse.ProtoReflect.Descriptor instead.
func (*SubscribeChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeChannelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscribeChannelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnsubscribeChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeChannelRequest) Reset() {
	*x = UnsubscribeChannelRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeChannelRequest) ProtoMessage() {}

func (x *UnsubscribeChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeChannelRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{11}
}

func (x *UnsubscribeChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UnsubscribeChannelRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type UnsubscribeChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeChannelResponse) Reset() {
	*x = UnsubscribeChannelResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeChannelResponse) ProtoMessage() {}

func (x *UnsubscribeChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeChannelResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{12}
}

func (x *UnsubscribeChannelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnsubscribeChannelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSubscribedChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribedChannelsRequest) Reset() {
	*x = GetSubscribedChannelsRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribedChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribedChannelsRequest) ProtoMessage() {}

func (x *GetSubscribedChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribedChannelsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscribedChannelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{13}
}

func (x *GetSubscribedChannelsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetSubscribedChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*Channel             `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscribedChannelsResponse) Reset() {
	*x = GetSubscribedChannelsResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscribedChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscribedChannelsResponse) ProtoMessage() {}

func (x *GetSubscribedChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscribedChannelsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscribedChannelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{14}
}

func (x *GetSubscribedChannelsResponse) GetChannels() []*Channel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type Channel struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ChannelId         string                 `protobuf:"bytes,3,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	LastLiveScheduled *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_live_scheduled,json=lastLiveScheduled,proto3" json:"last_live_scheduled,omitempty"`
	IsLive            bool                   `protobuf:"varint,5,opt,name=is_live,json=isLive,proto3" json:"is_live,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_proto_oshizatsu_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{15}
}

func (x *Channel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Channel) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Channel) GetLastLiveScheduled() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLiveScheduled
	}
	return nil
}

func (x *Channel) GetIsLive() bool {
	if x != nil {
		return x.IsLive
	}
	return false
}

// 通知関連のメッセージ
type RegisterFCMTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FcmToken      string                 `protobuf:"bytes,1,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFCMTokenRequest) Reset() {
	*x = RegisterFCMTokenRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFCMTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFCMTokenRequest) ProtoMessage() {}

func (x *RegisterFCMTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFCMTokenRequest.ProtoReflect.Descriptor instead.
func (*RegisterFCMTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterFCMTokenRequest) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

func (x *RegisterFCMTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RegisterFCMTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFCMTokenResponse) Reset() {
	*x = RegisterFCMTokenResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFCMTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFCMTokenResponse) ProtoMessage() {}

func (x *RegisterFCMTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFCMTokenResponse.ProtoReflect.Descriptor instead.
func (*RegisterFCMTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterFCMTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterFCMTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnregisterFCMTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FcmToken      string                 `protobuf:"bytes,1,opt,name=fcm_token,json=fcmToken,proto3" json:"fcm_token,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterFCMTokenRequest) Reset() {
	*x = UnregisterFCMTokenRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterFCMTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterFCMTokenRequest) ProtoMessage() {}

func (x *UnregisterFCMTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterFCMTokenRequest.ProtoReflect.Descriptor instead.
func (*UnregisterFCMTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{18}
}

func (x *UnregisterFCMTokenRequest) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

func (x *UnregisterFCMTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type UnregisterFCMTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterFCMTokenResponse) Reset() {
	*x = UnregisterFCMTokenResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterFCMTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterFCMTokenResponse) ProtoMessage() {}

func (x *UnregisterFCMTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterFCMTokenResponse.ProtoReflect.Descriptor instead.
func (*UnregisterFCMTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{19}
}

func (x *UnregisterFCMTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterFCMTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsRequest) Reset() {
	*x = GetNotificationsRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsRequest) ProtoMessage() {}

func (x *GetNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{20}
}

func (x *GetNotificationsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetNotificationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationsResponse) Reset() {
	*x = GetNotificationsResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationsResponse) ProtoMessage() {}

func (x *GetNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationsResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{21}
}

func (x *GetNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetNotificationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ChannelId     string                 `protobuf:"bytes,4,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,5,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	Type          NotificationType       `protobuf:"varint,6,opt,name=type,proto3,enum=oshizatsu.NotificationType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsRead        bool                   `protobuf:"varint,8,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_oshizatsu_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{22}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Notification) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *Notification) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_SCHEDULED
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

type MarkNotificationAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkNotificationAsReadRequest) Reset() {
	*x = MarkNotificationAsReadRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationAsReadRequest) ProtoMessage() {}

func (x *MarkNotificationAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{23}
}

func (x *MarkNotificationAsReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *MarkNotificationAsReadRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type MarkNotificationAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationAsReadResponse) Reset() {
	*x = MarkNotificationAsReadResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationAsReadResponse) ProtoMessage() {}

func (x *MarkNotificationAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkNotificationAsReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{24}
}

func (x *MarkNotificationAsReadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MarkNotificationAsReadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteNotificationRequest) Reset() {
	*x = DeleteNotificationRequest{}
	mi := &file_proto_oshizatsu_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationRequest) ProtoMessage() {}

func (x *DeleteNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *DeleteNotificationRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type DeleteNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNotificationResponse) Reset() {
	*x = DeleteNotificationResponse{}
	mi := &file_proto_oshizatsu_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNotificationResponse) ProtoMessage() {}

func (x *DeleteNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_oshizatsu_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNotificationResponse.ProtoReflect.Descriptor instead.
func (*DeleteNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_oshizatsu_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteNotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_oshizatsu_proto protoreflect.FileDescriptor

const file_proto_oshizatsu_proto_rawDesc = "" +
	"\n" +
	"\x15proto/oshizatsu.proto\x12\toshizatsu\x1a\x1fgoogle/protobuf/timestamp.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x89\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x120\n" +
	"\tuser_info\x18\x03 \x01(\v2\x13.oshizatsu.UserInfoR\buserInfo\"2\n" +
	"\rLogoutRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"7\n" +
	"\x12GetUserInfoRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"G\n" +
	"\x13GetUserInfoResponse\x120\n" +
	"\tuser_info\x18\x01 \x01(\v2\x13.oshizatsu.UserInfoR\buserInfo\"h\n" +
	"\x15UpdateUserInfoRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\x03 \x01(\tR\apicture\"~\n" +
	"\x16UpdateUserInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\tuser_info\x18\x03 \x01(\v2\x13.oshizatsu.UserInfoR\buserInfo\"^\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\apicture\x18\x04 \x01(\tR\apicture\"~\n" +
	"\x17SubscribeChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"N\n" +
	"\x18SubscribeChannelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x19UnsubscribeChannelRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"P\n" +
	"\x1aUnsubscribeChannelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x1cGetSubscribedChannelsRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"O\n" +
	"\x1dGetSubscribedChannelsResponse\x12.\n" +
	"\bchannels\x18\x01 \x03(\v2\x12.oshizatsu.ChannelR\bchannels\"\xb1\x01\n" +
	"\aChannel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x03 \x01(\tR\tchannelId\x12J\n" +
	"\x13last_live_scheduled\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11lastLiveScheduled\x12\x17\n" +
	"\ais_live\x18\x05 \x01(\bR\x06isLive\"Y\n" +
	"\x17RegisterFCMTokenRequest\x12\x1b\n" +
	"\tfcm_token\x18\x01 \x01(\tR\bfcmToken\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"N\n" +
	"\x18RegisterFCMTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"[\n" +
	"\x19UnregisterFCMTokenRequest\x12\x1b\n" +
	"\tfcm_token\x18\x01 \x01(\tR\bfcmToken\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"P\n" +
	"\x1aUnregisterFCMTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"j\n" +
	"\x17GetNotificationsRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"z\n" +
	"\x18GetNotificationsResponse\x12=\n" +
	"\rnotifications\x18\x01 \x03(\v2\x17.oshizatsu.NotificationR\rnotifications\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x8f\x02\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x04 \x01(\tR\tchannelId\x12!\n" +
	"\fchannel_name\x18\x05 \x01(\tR\vchannelName\x12/\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1b.oshizatsu.NotificationTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\ais_read\x18\b \x01(\bR\x06isRead\"k\n" +
	"\x1dMarkNotificationAsReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"T\n" +
	"\x1eMarkNotificationAsReadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"g\n" +
	"\x19DeleteNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\"P\n" +
	"\x1aDeleteNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*.\n" +
	"\x10NotificationType\x12\r\n" +
	"\tSCHEDULED\x10\x00\x12\v\n" +
	"\aSTARTED\x10\x012\xad\x02\n" +
	"\vAuthService\x12:\n" +
	"\x05Login\x12\x17.oshizatsu.LoginRequest\x1a\x18.oshizatsu.LoginResponse\x12=\n" +
	"\x06Logout\x12\x18.oshizatsu.LogoutRequest\x1a\x19.oshizatsu.LogoutResponse\x12L\n" +
	"\vGetUserInfo\x12\x1d.oshizatsu.GetUserInfoRequest\x1a\x1e.oshizatsu.GetUserInfoResponse\x12U\n" +
	"\x0eUpdateUserInfo\x12 .oshizatsu.UpdateUserInfoRequest\x1a!.oshizatsu.UpdateUserInfoResponse2\xbc\x02\n" +
	"\x0eChannelService\x12[\n" +
	"\x10SubscribeChannel\x12\".oshizatsu.SubscribeChannelRequest\x1a#.oshizatsu.SubscribeChannelResponse\x12a\n" +
	"\x12UnsubscribeChannel\x12$.oshizatsu.UnsubscribeChannelRequest\x1a%.oshizatsu.UnsubscribeChannelResponse\x12j\n" +
	"\x15GetSubscribedChannels\x12'.oshizatsu.GetSubscribedChannelsRequest\x1a(.oshizatsu.GetSubscribedChannelsResponse2\x84\x04\n" +
	"\x13NotificationService\x12[\n" +
	"\x10RegisterFCMToken\x12\".oshizatsu.RegisterFCMTokenRequest\x1a#.oshizatsu.RegisterFCMTokenResponse\x12a\n" +
	"\x12UnregisterFCMToken\x12$.oshizatsu.UnregisterFCMTokenRequest\x1a%.oshizatsu.UnregisterFCMTokenResponse\x12[\n" +
	"\x10GetNotifications\x12\".oshizatsu.GetNotificationsRequest\x1a#.oshizatsu.GetNotificationsResponse\x12m\n" +
	"\x16MarkNotificationAsRead\x12(.oshizatsu.MarkNotificationAsReadRequest\x1a).oshizatsu.MarkNotificationAsReadResponse\x12a\n" +
	"\x12DeleteNotification\x12$.oshizatsu.DeleteNotificationRequest\x1a%.oshizatsu.DeleteNotificationResponseB\x19Z\x17oshizatsu-backend/protob\x06proto3"

var (
	file_proto_oshizatsu_proto_rawDescOnce sync.Once
	file_proto_oshizatsu_proto_rawDescData []byte
)

func file_proto_oshizatsu_proto_rawDescGZIP() []byte {
	file_proto_oshizatsu_proto_rawDescOnce.Do(func() {
		file_proto_oshizatsu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_oshizatsu_proto_rawDesc), len(file_proto_oshizatsu_proto_rawDesc)))
	})
	return file_proto_oshizatsu_proto_rawDescData
}

var file_proto_oshizatsu_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_oshizatsu_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_proto_oshizatsu_proto_goTypes = []any{
	(NotificationType)(0),                  // 0: oshizatsu.NotificationType
	(*LoginRequest)(nil),                   // 1: oshizatsu.LoginRequest
	(*LoginResponse)(nil),                  // 2: oshizatsu.LoginResponse
	(*LogoutRequest)(nil),                  // 3: oshizatsu.LogoutRequest
	(*LogoutResponse)(nil),                 // 4: oshizatsu.LogoutResponse
	(*GetUserInfoRequest)(nil),             // 5: oshizatsu.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),            // 6: oshizatsu.GetUserInfoResponse
	(*UpdateUserInfoRequest)(nil),          // 7: oshizatsu.UpdateUserInfoRequest
	(*UpdateUserInfoResponse)(nil),         // 8: oshizatsu.UpdateUserInfoResponse
	(*UserInfo)(nil),                       // 9: oshizatsu.UserInfo
	(*SubscribeChannelRequest)(nil),        // 10: oshizatsu.SubscribeChannelRequest
	(*SubscribeChannelResponse)(nil),       // 11: oshizatsu.SubscribeChannelResponse
	(*UnsubscribeChannelRequest)(nil),      // 12: oshizatsu.UnsubscribeChannelRequest
	(*UnsubscribeChannelResponse)(nil),     // 13: oshizatsu.UnsubscribeChannelResponse
	(*GetSubscribedChannelsRequest)(nil),   // 14: oshizatsu.GetSubscribedChannelsRequest
	(*GetSubscribedChannelsResponse)(nil),  // 15: oshizatsu.GetSubscribedChannelsResponse
	(*Channel)(nil),                        // 16: oshizatsu.Channel
	(*RegisterFCMTokenRequest)(nil),        // 17: oshizatsu.RegisterFCMTokenRequest
	(*RegisterFCMTokenResponse)(nil),       // 18: oshizatsu.RegisterFCMTokenResponse
	(*UnregisterFCMTokenRequest)(nil),      // 19: oshizatsu.UnregisterFCMTokenRequest
	(*UnregisterFCMTokenResponse)(nil),     // 20: oshizatsu.UnregisterFCMTokenResponse
	(*GetNotificationsRequest)(nil),        // 21: oshizatsu.GetNotificationsRequest
	(*GetNotificationsResponse)(nil),       // 22: oshizatsu.GetNotificationsResponse
	(*Notification)(nil),                   // 23: oshizatsu.Notification
	(*MarkNotificationAsReadRequest)(nil),  // 24: oshizatsu.MarkNotificationAsReadRequest
	(*MarkNotificationAsReadResponse)(nil), // 25: oshizatsu.MarkNotificationAsReadResponse
	(*DeleteNotificationRequest)(nil),      // 26: oshizatsu.DeleteNotificationRequest
	(*DeleteNotificationResponse)(nil),     // 27: oshizatsu.DeleteNotificationResponse
	(*timestamppb.Timestamp)(nil),          // 28: google.protobuf.Timestamp
}
var file_proto_oshizatsu_proto_depIdxs = []int32{
	9,  // 0: oshizatsu.LoginResponse.user_info:type_name -> oshizatsu.UserInfo
	9,  // 1: oshizatsu.GetUserInfoResponse.user_info:type_name -> oshizatsu.UserInfo
	9,  // 2: oshizatsu.UpdateUserInfoResponse.user_info:type_name -> oshizatsu.UserInfo
	16, // 3: oshizatsu.GetSubscribedChannelsResponse.channels:type_name -> oshizatsu.Channel
	28, // 4: oshizatsu.Channel.last_live_scheduled:type_name -> google.protobuf.Timestamp
	23, // 5: oshizatsu.GetNotificationsResponse.notifications:type_name -> oshizatsu.Notification
	0,  // 6: oshizatsu.Notification.type:type_name -> oshizatsu.NotificationType
	28, // 7: oshizatsu.Notification.created_at:type_name -> google.protobuf.Timestamp
	1,  // 8: oshizatsu.AuthService.Login:input_type -> oshizatsu.LoginRequest
	3,  // 9: oshizatsu.AuthService.Logout:input_type -> oshizatsu.LogoutRequest
	5,  // 10: oshizatsu.AuthService.GetUserInfo:input_type -> oshizatsu.GetUserInfoRequest
	7,  // 11: oshizatsu.AuthService.UpdateUserInfo:input_type -> oshizatsu.UpdateUserInfoRequest
	10, // 12: oshizatsu.ChannelService.SubscribeChannel:input_type -> oshizatsu.SubscribeChannelRequest
	12, // 13: oshizatsu.ChannelService.UnsubscribeChannel:input_type -> oshizatsu.UnsubscribeChannelRequest
	14, // 14: oshizatsu.ChannelService.GetSubscribedChannels:input_type -> oshizatsu.GetSubscribedChannelsRequest
	17, // 15: oshizatsu.NotificationService.RegisterFCMToken:input_type -> oshizatsu.RegisterFCMTokenRequest
	19, // 16: oshizatsu.NotificationService.UnregisterFCMToken:input_type -> oshizatsu.UnregisterFCMTokenRequest
	21, // 17: oshizatsu.NotificationService.GetNotifications:input_type -> oshizatsu.GetNotificationsRequest
	24, // 18: oshizatsu.NotificationService.MarkNotificationAsRead:input_type -> oshizatsu.MarkNotificationAsReadRequest
	26, // 19: oshizatsu.NotificationService.DeleteNotification:input_type -> oshizatsu.DeleteNotificationRequest
	2,  // 20: oshizatsu.AuthService.Login:output_type -> oshizatsu.LoginResponse
	4,  // 21: oshizatsu.AuthService.Logout:output_type -> oshizatsu.LogoutResponse
	6,  // 22: oshizatsu.AuthService.GetUserInfo:output_type -> oshizatsu.GetUserInfoResponse
	8,  // 23: oshizatsu.AuthService.UpdateUserInfo:output_type -> oshizatsu.UpdateUserInfoResponse
	11, // 24: oshizatsu.ChannelService.SubscribeChannel:output_type -> oshizatsu.SubscribeChannelResponse
	13, // 25: oshizatsu.ChannelService.UnsubscribeChannel:output_type -> oshizatsu.UnsubscribeChannelResponse
	15, // 26: oshizatsu.ChannelService.GetSubscribedChannels:output_type -> oshizatsu.GetSubscribedChannelsResponse
	18, // 27: oshizatsu.NotificationService.RegisterFCMToken:output_type -> oshizatsu.RegisterFCMTokenResponse
	20, // 28: oshizatsu.NotificationService.UnregisterFCMToken:output_type -> oshizatsu.UnregisterFCMTokenResponse
	22, // 29: oshizatsu.NotificationService.GetNotifications:output_type -> oshizatsu.GetNotificationsResponse
	25, // 30: oshizatsu.NotificationService.MarkNotificationAsRead:output_type -> oshizatsu.MarkNotificationAsReadResponse
	27, // 31: oshizatsu.NotificationService.DeleteNotification:output_type -> oshizatsu.DeleteNotificationResponse
	20, // [20:32] is the sub-list for method output_type
	8,  // [8:20] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_oshizatsu_proto_init() }
func file_proto_oshizatsu_proto_init() {
	if File_proto_oshizatsu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_oshizatsu_proto_rawDesc), len(file_proto_oshizatsu_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_oshizatsu_proto_goTypes,
		DependencyIndexes: file_proto_oshizatsu_proto_depIdxs,
		EnumInfos:         file_proto_oshizatsu_proto_enumTypes,
		MessageInfos:      file_proto_oshizatsu_proto_msgTypes,
	}.Build()
	File_proto_oshizatsu_proto = out.File
	file_proto_oshizatsu_proto_goTypes = nil
	file_proto_oshizatsu_proto_depIdxs = nil
}
